#!/bin/bash

# create files
openssl rand -out file-xs.txt 100
openssl rand -out file-s.txt 10000
openssl rand -out file-m.txt 1000000
openssl rand -out file-lg.txt 100000000

# cipher algorithms
algos=["des-cbc" "des-ede3" "rc4" "aes-128-cbc" "aes-192-cbc" "aes-256-cbc" "chacha20"]
keys=[]
ivs=[]

for algo in $algos; do
  echo algo
done


# remove files
rm file-xs.txt
rm file-s.txt
rm file-m.txt
rm file-lg.txt
